upstream backend_laravel {
    server laravel.test:8000;        # Prioritas 1: Swoole
    server laravel.test:9000 backup; # Prioritas 2: PHP-FPM (Cadangan)
}

server {
    listen 80;

    location / {
        proxy_pass http://backend_laravel; # Nginx bakal milih mana yang nyala
        proxy_next_upstream error timeout invalid_header http_502;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
